spring.application.name=servico-auditor-dlq

spring.datasource.url=jdbc:h2:file:./data/dlq-audit-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

aws.sqs.listener.enabled=true
aws.sqs.queue.dlq-name=${AUDIT_DLQ_QUEUE_NAME:T04N_VINICIUS_CECATTO-DLQ.fifo}
